name: 'Run sonar-scanner'
description: 'Run sonar-scanner'
inputs:
  sonar-properties-path:
    description: 'Path to sonar-scanner.properties, can be relative to working directory'
    required: false
    default: '.sonarqube/sonar-scanner.properties'
  sonar-token:
    description: 'Token for use with SonarCloud'
    required: true
  working-dir:
    description: 'Top directory to run sonar-scanner from'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Environment
      shell: bash
      env:
        PR_HEAD_REF: ${{ github.head_ref }}
      run: |
        INIT_ENV="/home/carma/.base-image/init-env.sh"
        if [ -f "$INIT_ENV" ]; then
          source "$INIT_ENV"
        fi

        INIT_ENV="/home/carma-streets/.base-image/init-env.sh"
        if [ -f "$INIT_ENV" ]; then
          source "$INIT_ENV"
        fi

        if [ -d "${{ inputs.working-dir }}" ]; then
          cd "${{ inputs.working-dir }}" || exit 1
        else
          echo "Directory does not exist!: ${{ inputs.working-dir }}"
        fi

        if [ ! -f "${{ inputs.sonar-properties-path }}" ]; then
          echo "File does not exist!: ${{ inputs.sonar-properties-path }}"
          exit 1
        fi
    - name: SonarQube Scan Pull Request
      if: github.event_name == 'pull_request'
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        working-directory: ${{ inputs.working-dir }}
        # Consult https://docs.sonarsource.com/sonarqube-server/latest/analyzing-source-code/scanners/sonarscanner/ for more information and options
        args: >
          -Dproject.settings="${{ inputs.sonar-properties-path }}" 
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }} 
          -Dsonar.pullrequest.branch=$PR_HEAD_REF 
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
    - name: SonarQube Scan main branch
      if: github.event_name != 'pull_request'
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        working-directory: ${{ inputs.working-dir }}
        # Consult https://docs.sonarsource.com/sonarqube-server/latest/analyzing-source-code/scanners/sonarscanner/ for more information and options
        args: >
          -Dproject.settings="${{ inputs.sonar-properties-path }}" 
