name: 'Determine STOL Organization and Tag for Docker Images '
description: 'Based on github event trigger, this action determines and outputs the dockerhub organization and image tag to pull/push images from/to.'
outputs:
  docker_organization:
    description: 'Dockerhub organization for images'
  docker_image_tag:
    description: 'Docker image tag'
runs:
  using: 'composite'
  steps:
    - name: Determine git tag
      shell: bash
      if: contains(github.ref, 'refs/tags/')
      run: |
        GIT_TAG="$(git tag --points-at HEAD)"
        if [ -z "$GIT_TAG" ]; then
            echo "No git tag found for commit $GITHUB_SHA"
            echo "This is required for pushing master to Docker Hub"
            echo "Tag the commit with a version number and try again"
            exit 1
        else
            echo "Found git tag $GIT_TAG"
            echo GIT_TAG="$GIT_TAG" >> $GITHUB_ENV
        fi
    - name: Determine Docker Hub org and tag from Git Branch
      shell: bash
      if: github.event_name != 'pull_request'
      run: |
        if [[ "$GITHUB_REF_NAME" =~ release/(.*) ]]; then
            echo DOCKERHUB_ORG="usdotfhwastolcandidate" >> $GITHUB_OUTPUT
            echo DOCKERHUB_TAG="${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
        elif [ "$GITHUB_REF_NAME" == "carma-master" ] || [ "$GITHUB_REF_NAME" == "master" ] || [[ "$GIT_TAG" != "" ]]; then
            echo DOCKERHUB_ORG="usdotfhwastol" >> $GITHUB_OUTPUT
            echo DOCKERHUB_TAG="$GIT_TAG" >> $GITHUB_OUTPUT
        else
            echo DOCKERHUB_ORG="usdotfhwastoldev" >> $GITHUB_OUTPUT
            if [ "$GITHUB_REF_NAME" == "carma-develop" ]; then
                echo DOCKERHUB_TAG="develop" >> $GITHUB_OUTPUT
            else
                # Replace / with - in branch name
                echo DOCKERHUB_TAG=${GITHUB_REF_NAME/\//-} >> $GITHUB_OUTPUT
            fi
        fi
    - name: Determine Docker Hub org and tag from Pull Request
      shell: bash
      if: github.event_name == 'pull_request'
      run: |
        if [[ "$GITHUB_HEAD_REF" =~ release/(.*) ]]; then
            echo DOCKERHUB_ORG="usdotfhwastolcandidate" >> $GITHUB_OUTPUT
            echo DOCKERHUB_TAG="${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
        elif [ "$GITHUB_HEAD_REF" == "carma-master" ] || [ "$GITHUB_HEAD_REF" == "master" ] || [[ "$GIT_TAG" != "" ]]; then
            echo DOCKERHUB_ORG="usdotfhwastol" >> $GITHUB_OUTPUT
            echo DOCKERHUB_TAG="$GIT_TAG" >> $GITHUB_OUTPUT
        else
            echo DOCKERHUB_ORG="usdotfhwastoldev" >> $GITHUB_OUTPUT
            if [ "$GITHUB_HEAD_REF" == "carma-develop" ]; then
                echo DOCKERHUB_TAG="develop" >> $GITHUB_OUTPUT
            else
                # Replace / with - in branch name
                echo DOCKERHUB_TAG=${GITHUB_HEAD_REF/\//-} >> $GITHUB_OUTPUT
            fi
        fi