name: 'Setup deb-s3'
description: 'Setup deb-s3'
inputs:
  mk-build-deps:
    description: 'Install mk-build-deps'
    required: false
    default: 'false'
  bloom:
    description: 'Install python3-bloom'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install deb-s3
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/setup.sh
        if [ "$(id --user)" -eq "0" ]; then
          sudocmd=""
        else
          sudocmd="sudo"
        fi

        if [ "${{ inputs.mk-build-deps }}" == "true" ]; then
          $sudocmd apt-get -y install debhelper devscripts equivs
        fi

        if [ "${{ inputs.bloom }}" == "true" ]; then
          $sudocmd apt-get -y install python3-bloom
        fi