name: 'Debian S3 Upload'
description: 'Upload any debian packages to the S3 repo based on a passed in artifact name. Assumes deb-s3 is available'
inputs:
  artifact-name:
    description: 'Artifact name containing debian packages'
    required: true
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-bucket-name:
    description: 'AWS bucket name, defaults to stol-apt-repository'
    default: 'stol-apt-repository'
  bucket-codename:
    description: 'Bucket codename, defaults to null, which will determine the codename using determine_codename.sh'
    required: false
    default: ''
  component-name:
    description: 'The component of the APT repository. This should be equivalent to ubuntu distribution code name that this artifact supports'
    required: true
  architecture:
    description: 'Hardware architecture for package'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Download deb artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: deb-packages
    - name: Upload .deb files
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_BUCKET_NAME: ${{ inputs.aws-bucket-name }}
      shell: bash
      run: |
        if [ -z "${{ inputs.bucket-codename }}" ]; then
          CODENAME=$(${GITHUB_ACTION_PATH}/determine_codename.sh)
        else
          CODENAME=${{ inputs.bucket-codename }}
        fi
        echo "Using CODENAME: $CODENAME"
        if [ -z "${{ inputs.architecture }}" ]; then
          if [[ "${{ inputs.arctifact-name }}" == *"arm64"* ]]; then
            ARCHITECTURE="arm64"
          elif [[ "${{ inputs.arctifact-name }}" == *"amd64"* ]]; then
            ARCHITECTURE="amd64"
          else
            echo "Unknown architecture"
          fi
        else
          ARCHITECTURE=${{ inputs.architecture }}
        fi
        echo "Using architecture : $ARCHITECTURE"

        find deb-packages -name "*.deb" -print0 | xargs -0 deb-s3 upload --origin=${{ env.AWS_BUCKET_NAME }} --codename ${CODENAME} --component ${{ inputs.component-name }} --bucket ${{ env.AWS_BUCKET_NAME }} --arch $ARCHITECTURE
