name: C++ Module Build workflow

on:
  workflow_call:
    inputs:
      build-image-tag:
        description: 'Build image tag for ghcr.io/usdot-fhwa-stol/carma-builds'
        required: false
        type: string
        default: 'latest'
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  image-name-get:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: echo "image=${{ inputs.build-image-tag }}" >> $GITHUB_OUTPUT
  git-revision-info-get:
    runs-on: ubuntu-latest
    outputs:
      git-revision-info: ${{ steps.get_git_info.outputs.revision_info }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get_git_info
        run: |
          echo GITHUB_REF_TYPE=${GITHUB_REF_TYPE}
          if [ "${GITHUB_REF_TYPE}" == "branch" ]; then
             echo "revision_info=$(date +%Y%m%d).git$(git rev-list --count HEAD).$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi
  cpp-module-build:
    runs-on: ubuntu-latest
    needs:
      - image-name-get
      - git-revision-info-get
    container:
      image: ghcr.io/usdot-fhwa-stol/carma-builds:${{ needs.image-name-get.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          if [ -f install_dependencies.sh ]; then
            apt-get update
            ./install_dependencies.sh
          fi # check file existence
      - name: Build
        uses: usdot-fhwa-stol/actions/build-cpp-library@debian_beta_packages
        with:
          git-revision-info: ${{ needs.git-revision-info-get.outputs.git-revision-info }}
      - name: Setup deb-s3
        uses: usdot-fhwa-stol/actions/setup-deb-s3@main
      - name: Upload .deb files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
          AWS_BUCKET_NAME: stol-apt-repository
        run: |
          deb-s3 upload --codename develop --bucket ${{ env.AWS_BUCKET_NAME }} build/_packages/*.deb
