name: C++ Module Build workflow

on:
  workflow_call:
    inputs:
      build-architecture:
        description: 'Build architecture, defaults x64, see the carma-builds project for supported architectures'
        required: false
        type: string
        default: 'x64'
      build-image-tag:
        description: 'Build image tag for ghcr.io/usdot-fhwa-stol/carma-builds'
        required: false
        type: string
        default: 'latest'
      working-folder:
        description: 'Working folder to build in'
        type: string
        required: false
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  image-name-get:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: |
          BUILD_ARCHITECTURE="-${{ inputs.build-architecture }}"
          echo "image=carma-builds${BUILD_ARCHITECTURE}:${{ inputs.build-image-tag }}" >> $GITHUB_OUTPUT
  git-revision-info-get:
    uses: usdot-fhwa-stol/actions/.github/workflows/git-revision-info.yml@main
  cpp-module-build:
    runs-on: ubuntu-latest
    needs:
      - image-name-get
      - git-revision-info-get
    container:
      image: ghcr.io/usdot-fhwa-stol/${{ needs.image-name-get.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          if [ -f install_dependencies.sh ]; then
            ./install_dependencies.sh
          fi # check file existence
      - name: Build
        uses: usdot-fhwa-stol/actions/build-cpp-library@repo_codename_setup
        with:
          package-version-suffix: ${{ needs.git-revision-info-get.outputs.git-revision-info }}
          working-folder: ${{ inputs.working-folder }}
      - name: Upload deb artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deb-packages-${{ inputs.build-architecture }}
          path: |
            build*/_packages/*.deb
            ${{ inputs.working-folder }}/build*/_packages/*.deb

  deb-s3-upload:
    runs-on: ubuntu-latest
    needs:
      - cpp-module-build
    container:
      image: ghcr.io/usdot-fhwa-stol/actions-deb-s3:main
    steps:
      - name: Publish deb artifacts
        uses: usdot-fhwa-stol/actions/deb-s3-upload@repo_codename_setup
        with:
          artifact-name: deb-packages-${{ inputs.build-architecture }}
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
