name: Docker Build

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: false
    inputs:
      context:
        description: "Optional: List of Additional Build Contexts"
        type: "string"
        required: false
      file:
        description: "Optional: Path to Dockerfile"
        type: "string"
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Determine Docker organization and tag
        id: docker-org-and-tag
        uses: usdot-fhwa-stol/actions/docker-org-and-tag@main
      - name: Determine base branch
        id: determine-base-branch
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo git_branch="$GITHUB_BASE_REF" >> $GITHUB_OUTPUT
          else
            echo git_branch="$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          fi
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          build-args: |
            TOKEN=${{ secrets.GH_PAT }}
            DOCKER_ORG=${{ steps.docker-org-and-tag.outputs.docker_organization }}
            DOCKER_TAG=${{ steps.docker-org-and-tag.outputs.docker_image_tag }}
            GIT_BRANCH=${{ steps.determine-base-branch.outputs.git_branch}}
