name: Docker Build

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: false
    inputs:
      context:
        description: "Optional: List of Additional Build Contexts"
        type: "string"
        required: false
      file:
        description: "Optional: Path to Dockerfile"
        type: "string"
        required: false
      github_submodules:
        description: "Optional: Boolean flag to indicate whether repository contains github submodules"
        type: "boolean"
        required: false
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          build-args: |
            TOKEN=${{ secrets.GH_PAT }}
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=${{ inputs.github_submodules }}
            

