name: Docker Build

on:
  workflow_call:
    secrets:
      GH_PAT:
        description: "GITHUB Token for accessing private stol github repositories"
        required: false
      ACCESS_ID:
        description: "Access ID for accessing astuff s3 apt repository"
        required: false
      SECRET_KEY:
        description: "Secret Key for accessing astuff s3 apt repository"
        required: false
    inputs:
      context:
        description: "Build's context is the set of files located in the specified PATH or URL (default .)"
        type: "string"
        default: .
      file:
        description: "Optional: Path to Dockerfile"
        type: "string"
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Determine Docker organization and tag
        id: docker-org-and-tag
        uses: usdot-fhwa-stol/actions/docker-org-and-tag@main
      - name: Determine base branch
        id: determine-base-branch
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo git_branch="$GITHUB_BASE_REF" >> $GITHUB_OUTPUT
          else
            echo git_branch="$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          fi
          df -h
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true
      - name: Report space
        id: report-space
        run: |
          df -h
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          build-args: |
            TOKEN=${{ secrets.GH_PAT }}
            DOCKER_ORG=${{ steps.docker-org-and-tag.outputs.docker_organization }}
            DOCKER_TAG=${{ steps.docker-org-and-tag.outputs.docker_image_tag }}
            GIT_BRANCH=${{ steps.determine-base-branch.outputs.git_branch}}
            ACCESS_ID=${{ secrets.ACCESS_ID}}
            SECRET_KEY=${{ secrets.SECRET_KEY}}
